# Generated by Django 4.2.1 on 2023-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='proid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
