# Generated by Django 4.2.1 on 2023-05-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
