# Generated by Django 4.2.1 on 2023-07-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='password',
        ),
    ]
