# Generated by Django 4.2.1 on 2023-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_cart_products_delete_ordered_remove_orders_ordername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
