# Generated by Django 4.2.1 on 2023-07-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_products_pimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='plink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
