# Generated by Django 4.2.1 on 2023-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_products_plink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pimg',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
