# Generated by Django 4.2.1 on 2023-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_products_pimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
