# Generated by Django 4.2.1 on 2023-07-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
