# Generated by Django 4.2.1 on 2023-07-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='proname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='oname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
