# Generated by Django 4.2.1 on 2023-07-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_cart_proname_orders_oname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='memid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
